---
- name: Ensure overlay-friendly sysctls & modules on all nodes
  hosts: kafka_cluster
  become: true
  gather_facts: no

  tasks:
    - name: Load nf_conntrack now
      modprobe:
        name: nf_conntrack
        state: present

    - name: Persist kernel modules across reboots
      copy:
        dest: /etc/modules-load.d/k8s-net.conf
        mode: "0644"
        content: |
          br_netfilter
          nf_conntrack

    - name: Write overlay-safe rp_filter & netfilter sysctls
      copy:
        dest: /etc/sysctl.d/98-k8s-overlay.conf
        mode: "0644"
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.conf.all.rp_filter = 0
          net.ipv4.conf.default.rp_filter = 0

    - name: Apply sysctl config
      command: sysctl --system
      changed_when: false

- name: Restart kube-proxy and bounce CoreDNS
  hosts: "{{ groups['kafka_broker'][0] }}"
  become: true
  gather_facts: no

  vars:
    kubeconfig: /etc/kubernetes/admin.conf

  tasks:
    - name: Restart kube-proxy DS
      command: kubectl -n kube-system rollout restart ds/kube-proxy --kubeconfig {{ kubeconfig }}
    - name: Wait for kube-proxy Ready
      command: kubectl -n kube-system rollout status ds/kube-proxy --timeout=180s --kubeconfig {{ kubeconfig }}
      changed_when: false
    - name: Restart CoreDNS
      command: kubectl -n kube-system rollout restart deploy/coredns --kubeconfig {{ kubeconfig }}
    - name: Wait for CoreDNS
      command: kubectl -n kube-system rollout status deploy/coredns --timeout=120s --kubeconfig {{ kubeconfig }}
      changed_when: false
